<dec f='codebrowser/nscd/nscd-client.h' l='327' type='nscd_ssize_t'/>
<offset>320</offset>
<use f='codebrowser/nscd/nscd_helper.c' l='346' u='r' c='__nscd_get_mapping'/>
<use f='codebrowser/nscd/nscd_helper.c' l='358' u='r' c='__nscd_get_mapping'/>
<use f='codebrowser/nscd/nscd_helper.c' l='358' u='r' c='__nscd_get_mapping'/>
<use f='codebrowser/nscd/nscd_helper.c' l='373' u='r' c='__nscd_get_mapping'/>
<use f='codebrowser/nscd/nscd_helper.c' l='373' u='r' c='__nscd_get_mapping'/>
<use f='codebrowser/nscd/nscd_helper.c' l='454' u='r' c='__nscd_cache_search'/>
