<dec f='codebrowser/nss/nss_action.h' l='36' type='struct nss_module *'/>
<offset>0</offset>
<doc f='codebrowser/nss/nss_action.h' l='34'>/* The service module that provides the functionality (potentially
     not yet loaded).  */</doc>
<use f='codebrowser/grp/initgroups.c' l='91' u='r' c='internal_getgrouplist'/>
<use f='codebrowser/nss/nss_action.c' l='52' u='r' c='actions_equal'/>
<use f='codebrowser/nss/nss_action.c' l='52' u='r' c='actions_equal'/>
<use f='codebrowser/nss/nss_action_parse.c' l='57' u='w' c='nss_action_parse'/>
<use f='codebrowser/nss/nss_action_parse.c' l='58' u='r' c='nss_action_parse'/>
<use f='codebrowser/nss/nss_action_parse.c' l='173' u='w' c='__nss_action_parse'/>
<use f='codebrowser/nss/nsswitch.c' l='114' u='r' c='__nss_lookup'/>
<use f='codebrowser/nss/nsswitch.c' l='123' u='r' c='__nss_lookup'/>
<use f='codebrowser/nss/nsswitch.c' l='154' u='r' c='__nss_next2'/>
<use f='codebrowser/nss/nsswitch.c' l='167' u='r' c='__nss_next2'/>
<use f='codebrowser/nss/nsswitch.c' l='176' u='r' c='__nss_lookup_function'/>
<use f='codebrowser/nss/nsswitch.c' l='178' u='r' c='__nss_lookup_function'/>
<use f='codebrowser/sysdeps/posix/getaddrinfo.c' l='905' u='r' c='gaih_inet'/>
