<dec f='codebrowser/iconv/iconvconfig.h' l='59' type='struct extra_entry_module[0]'/>
<use f='codebrowser/iconv/gconv_cache.c' l='297' u='m' c='__gconv_lookup_cache'/>
<use f='codebrowser/iconv/gconv_cache.c' l='322' u='m' c='__gconv_lookup_cache'/>
<use f='codebrowser/iconv/gconv_cache.c' l='328' u='m' c='__gconv_lookup_cache'/>
<use f='codebrowser/iconv/gconv_cache.c' l='333' u='m' c='__gconv_lookup_cache'/>
<use f='codebrowser/iconv/gconv_cache.c' l='334' u='m' c='__gconv_lookup_cache'/>
<use f='codebrowser/iconv/gconv_cache.c' l='347' u='m' c='__gconv_lookup_cache'/>
<offset>16</offset>
