<dec f='codebrowser/iconv/iconvconfig.h' l='58' type='struct extra_entry_module[0]'/>
<use f='codebrowser/iconv/gconv_cache.c' l='296' u='m' c='__gconv_lookup_cache'/>
<use f='codebrowser/iconv/gconv_cache.c' l='321' u='m' c='__gconv_lookup_cache'/>
<use f='codebrowser/iconv/gconv_cache.c' l='327' u='m' c='__gconv_lookup_cache'/>
<use f='codebrowser/iconv/gconv_cache.c' l='332' u='m' c='__gconv_lookup_cache'/>
<use f='codebrowser/iconv/gconv_cache.c' l='333' u='m' c='__gconv_lookup_cache'/>
<use f='codebrowser/iconv/gconv_cache.c' l='346' u='m' c='__gconv_lookup_cache'/>
<offset>16</offset>
<use f='codebrowser/iconv/iconvconfig.c' l='1115' u='m' c='write_output'/>
<use f='codebrowser/iconv/iconvconfig.c' l='1118' u='m' c='write_output'/>
<use f='codebrowser/iconv/iconvconfig.c' l='1120' u='m' c='write_output'/>
